-- MySQL Script generated by MySQL Workbench
-- 07/09/20 18:16:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gameUpDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gameUpDB` ;

-- -----------------------------------------------------
-- Schema gameUpDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gameUpDB` DEFAULT CHARACTER SET utf8 ;
USE `gameUpDB` ;

-- -----------------------------------------------------
-- Table `gameUpDB`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Empresa` (
  `emp_id` INT NOT NULL AUTO_INCREMENT,
  `emp_cnpj` VARCHAR(20) NOT NULL,
  `emp_nome` VARCHAR(100) NULL,
  PRIMARY KEY (`emp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameUpDB`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`TipoUsuario` (
  `tus_id` INT NOT NULL AUTO_INCREMENT,
  `tus_descricao` VARCHAR(50) NULL,
  PRIMARY KEY (`tus_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameUpDB`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Setor` (
  `set_id` INT NOT NULL AUTO_INCREMENT,
  `set_nome` VARCHAR(100) NULL,
  `emp_id` INT NOT NULL,
  `usu_idGerente` INT NULL,
  `set_status` INT NULL,
  PRIMARY KEY (`set_id`),
  CONSTRAINT `fk_Setor_Empresa1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `gameUpDB`.`Empresa` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Setor_Usuario1`
    FOREIGN KEY (`usu_idGerente`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Setor_Empresa1_idx` ON `gameUpDB`.`Setor` (`emp_id` ASC);

CREATE INDEX `fk_Setor_Usuario1_idx` ON `gameUpDB`.`Setor` (`usu_idGerente` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Nivel` (
  `niv_id` INT NOT NULL AUTO_INCREMENT,
  `niv_xp` INT NULL,
  PRIMARY KEY (`niv_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameUpDB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_nome` VARCHAR(255) NOT NULL,
  `usu_dataNascimento` DATETIME NULL,
  `usu_email` VARCHAR(200) NOT NULL,
  `usu_senha` TEXT NULL,
  `usu_statusUsuario` INT NULL,
  `usu_apelido` VARCHAR(70) NULL,
  `usu_qtdMoeda` INT(1) ZEROFILL UNSIGNED NULL DEFAULT 0,
  `usu_qtdXp` INT(1) ZEROFILL UNSIGNED NULL DEFAULT 0,
  `usu_qtdPontos` INT(1) ZEROFILL UNSIGNED NULL DEFAULT 0,
  `tus_id` INT NOT NULL,
  `set_id` INT NULL,
  `usu_idGerente` INT NULL,
  `niv_id` INT NOT NULL,
  `emp_id` INT NOT NULL,
  PRIMARY KEY (`usu_id`),
  CONSTRAINT `fk_Usuario_TipoUsuario1`
    FOREIGN KEY (`tus_id`)
    REFERENCES `gameUpDB`.`TipoUsuario` (`tus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Setor1`
    FOREIGN KEY (`set_id`)
    REFERENCES `gameUpDB`.`Setor` (`set_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Usuario1`
    FOREIGN KEY (`usu_idGerente`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Nivel1`
    FOREIGN KEY (`niv_id`)
    REFERENCES `gameUpDB`.`Nivel` (`niv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Empresa1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `gameUpDB`.`Empresa` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_TipoUsuario1_idx` ON `gameUpDB`.`Usuario` (`tus_id` ASC);

CREATE INDEX `fk_Usuario_Setor1_idx` ON `gameUpDB`.`Usuario` (`set_id` ASC);

CREATE INDEX `fk_Usuario_Usuario1_idx` ON `gameUpDB`.`Usuario` (`usu_idGerente` ASC);

CREATE INDEX `fk_Usuario_Nivel1_idx` ON `gameUpDB`.`Usuario` (`niv_id` ASC);

CREATE INDEX `fk_Usuario_Empresa1_idx` ON `gameUpDB`.`Usuario` (`emp_id` ASC);

CREATE UNIQUE INDEX `usu_email_UNIQUE` ON `gameUpDB`.`Usuario` (`usu_email` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`Missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Missao` (
  `mis_id` INT NOT NULL AUTO_INCREMENT,
  `mis_nome` VARCHAR(100) NULL,
  `mis_descricao` VARCHAR(255) NULL,
  `mis_dt_Criacao` DATETIME NULL,
  `mis_dt_Inicio` DATETIME NULL,
  `mis_dt_Final` DATETIME NULL,
  `mis_qtd_Pontos` INT NULL,
  `mis_qtd_Exp` INT NULL,
  `mis_qtd_moedas` INT NULL,
  `mis_tipo` VARCHAR(50) NULL,
  `mis_status` VARCHAR(100) NOT NULL,
  `emp_id` INT NOT NULL,
  `usu_criador_id` INT NOT NULL,
  PRIMARY KEY (`mis_id`),
  CONSTRAINT `fk_Missao_Empresa1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `gameUpDB`.`Empresa` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Missao_Usuario1`
    FOREIGN KEY (`usu_criador_id`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Missao_Empresa1_idx` ON `gameUpDB`.`Missao` (`emp_id` ASC);

CREATE INDEX `fk_Missao_Usuario1_idx` ON `gameUpDB`.`Missao` (`usu_criador_id` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`Missao_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Missao_Usuario` (
  `mus_id` INT NOT NULL AUTO_INCREMENT,
  `mus_dt_Atribuicao` DATETIME NULL,
  `mus_dt_Conclusao` DATETIME NULL,
  `mus_dt_Validacao` DATETIME NULL,
  `mus_arquivo` TEXT NULL,
  `mus_status` VARCHAR(100) NOT NULL,
  `mis_id` INT NOT NULL,
  `usu_id` INT NOT NULL,
  PRIMARY KEY (`mus_id`),
  CONSTRAINT `fk_MissaoUsuario_Missao1`
    FOREIGN KEY (`mis_id`)
    REFERENCES `gameUpDB`.`Missao` (`mis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MissaoUsuario_Usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MissaoUsuario_Missao1_idx` ON `gameUpDB`.`Missao_Usuario` (`mis_id` ASC);

CREATE INDEX `fk_MissaoUsuario_Usuario1_idx` ON `gameUpDB`.`Missao_Usuario` (`usu_id` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`Pacote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Pacote` (
  `pct_id` INT NOT NULL AUTO_INCREMENT,
  `pct_nome` VARCHAR(255) NULL,
  `pct_valor` DOUBLE NULL,
  `pct_status` INT NULL,
  `pct_dHValidade` DATETIME NOT NULL,
  PRIMARY KEY (`pct_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameUpDB`.`EmpresaPacote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`EmpresaPacote` (
  `ept_id` INT NOT NULL AUTO_INCREMENT,
  `ept_dHCompra` DATETIME NOT NULL,
  `emp_id` INT NOT NULL,
  `pct_id` INT NOT NULL,
  PRIMARY KEY (`ept_id`),
  CONSTRAINT `fk_EmpresaPacote_Empresa1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `gameUpDB`.`Empresa` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EmpresaPacote_Pacote1`
    FOREIGN KEY (`pct_id`)
    REFERENCES `gameUpDB`.`Pacote` (`pct_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EmpresaPacote_Empresa1_idx` ON `gameUpDB`.`EmpresaPacote` (`emp_id` ASC);

CREATE INDEX `fk_EmpresaPacote_Pacote1_idx` ON `gameUpDB`.`EmpresaPacote` (`pct_id` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`TipoItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`TipoItem` (
  `tip_id` INT NOT NULL AUTO_INCREMENT,
  `tip_descricao` VARCHAR(50) NULL,
  PRIMARY KEY (`tip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameUpDB`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Produtos` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_nome` VARCHAR(100) NULL,
  `pro_subTitulo` VARCHAR(50) NULL,
  `pro_descricao` VARCHAR(255) NULL,
  `pro_valorMoeda` INT NULL,
  `pro_logo` TEXT NULL,
  `pro_status` INT NULL,
  `emp_id` INT NOT NULL,
  `usu_id` INT NOT NULL,
  `tip_id` INT NOT NULL,
  PRIMARY KEY (`pro_id`, `emp_id`),
  CONSTRAINT `fk_Produtos_Empresa1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `gameUpDB`.`Empresa` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_Usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_TipoItem1`
    FOREIGN KEY (`tip_id`)
    REFERENCES `gameUpDB`.`TipoItem` (`tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produtos_Empresa1_idx` ON `gameUpDB`.`Produtos` (`emp_id` ASC);

CREATE INDEX `fk_Produtos_Usuario1_idx` ON `gameUpDB`.`Produtos` (`usu_id` ASC);

CREATE INDEX `fk_Produtos_TipoItem1_idx` ON `gameUpDB`.`Produtos` (`tip_id` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`Conquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Conquista` (
  `con_id` INT NOT NULL AUTO_INCREMENT,
  `con_nome` VARCHAR(100) NULL,
  `con_descricao` VARCHAR(255) NULL,
  `con_valorXp` INT NULL,
  `con_valorPonto` INT NULL,
  `con_status` TINYINT(1) NULL,
  PRIMARY KEY (`con_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameUpDB`.`UsuarioConquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`UsuarioConquista` (
  `usc_id` INT NOT NULL AUTO_INCREMENT,
  `usc_dHConclusao` DATETIME NULL,
  `usu_id` INT NOT NULL,
  `con_id` INT NOT NULL,
  PRIMARY KEY (`usc_id`),
  CONSTRAINT `fk_UsuarioConquista_Usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioConquista_Conquista1`
    FOREIGN KEY (`con_id`)
    REFERENCES `gameUpDB`.`Conquista` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_UsuarioConquista_Usuario1_idx` ON `gameUpDB`.`UsuarioConquista` (`usu_id` ASC);

CREATE INDEX `fk_UsuarioConquista_Conquista1_idx` ON `gameUpDB`.`UsuarioConquista` (`con_id` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`MovEstoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`MovEstoque` (
  `mes_id` INT NOT NULL AUTO_INCREMENT,
  `mes_dHCriacao` DATETIME NULL,
  `mes_qtdEntrada` INT NOT NULL,
  `mes_qtdSaida` INT(1) ZEROFILL UNSIGNED NULL DEFAULT 0,
  `mes_saldo` INT(1) GENERATED ALWAYS AS (mes_qtdEntrada - mes_qtdSaida) VIRTUAL,
  `mes_descricao` VARCHAR(70) NULL,
  `pro_id` INT NOT NULL,
  `emp_id` INT NOT NULL,
  PRIMARY KEY (`mes_id`),
  CONSTRAINT `fk_MovEstoque_Produtos1`
    FOREIGN KEY (`pro_id` , `emp_id`)
    REFERENCES `gameUpDB`.`Produtos` (`pro_id` , `emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MovEstoque_Produtos1_idx` ON `gameUpDB`.`MovEstoque` (`pro_id` ASC, `emp_id` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`MovFinanceira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`MovFinanceira` (
  `mfi_id` INT NOT NULL AUTO_INCREMENT,
  `mfi_valorProd` DOUBLE NULL,
  `mfi_qtdProd` INT NULL,
  `mfi_dHCompra` DATETIME NULL,
  `pro_id` INT NOT NULL,
  `emp_id` INT NOT NULL,
  `usu_id` INT NOT NULL,
  PRIMARY KEY (`mfi_id`, `pro_id`, `emp_id`, `usu_id`),
  CONSTRAINT `fk_MovFinanceira_Produtos1`
    FOREIGN KEY (`pro_id` , `emp_id`)
    REFERENCES `gameUpDB`.`Produtos` (`pro_id` , `emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovFinanceira_Usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MovFinanceira_Produtos1_idx` ON `gameUpDB`.`MovFinanceira` (`pro_id` ASC, `emp_id` ASC);

CREATE INDEX `fk_MovFinanceira_Usuario1_idx` ON `gameUpDB`.`MovFinanceira` (`usu_id` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`Titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Titulo` (
  `til_id` INT NOT NULL AUTO_INCREMENT,
  `til_descricao` VARCHAR(70) NULL,
  PRIMARY KEY (`til_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameUpDB`.`TituloConquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`TituloConquista` (
  `tco_id` INT NOT NULL AUTO_INCREMENT,
  `con_id` INT NOT NULL,
  `til_id` INT NOT NULL,
  PRIMARY KEY (`tco_id`),
  CONSTRAINT `fk_TituloConquista_Conquista1`
    FOREIGN KEY (`con_id`)
    REFERENCES `gameUpDB`.`Conquista` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TituloConquista_Titulo1`
    FOREIGN KEY (`til_id`)
    REFERENCES `gameUpDB`.`Titulo` (`til_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TituloConquista_Conquista1_idx` ON `gameUpDB`.`TituloConquista` (`con_id` ASC);

CREATE INDEX `fk_TituloConquista_Titulo1_idx` ON `gameUpDB`.`TituloConquista` (`til_id` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`UsuarioTitulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`UsuarioTitulo` (
  `usu_id` INT NOT NULL,
  `til_id` INT NOT NULL,
  `uxt_dH` DATETIME NULL,
  PRIMARY KEY (`usu_id`, `til_id`),
  CONSTRAINT `fk_Usuario_has_Titulo_Usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Titulo_Titulo1`
    FOREIGN KEY (`til_id`)
    REFERENCES `gameUpDB`.`Titulo` (`til_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Titulo_Titulo1_idx` ON `gameUpDB`.`UsuarioTitulo` (`til_id` ASC);

CREATE INDEX `fk_Usuario_has_Titulo_Usuario1_idx` ON `gameUpDB`.`UsuarioTitulo` (`usu_id` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`Suporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`Suporte` (
  `usu_id` INT NOT NULL,
  `usu_idMod` INT NULL,
  `sup_titulo` VARCHAR(50) NULL,
  `sup_descricao` VARCHAR(255) NULL,
  `sup_status` INT NULL,
  PRIMARY KEY (`usu_id`),
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario2`
    FOREIGN KEY (`usu_idMod`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Usuario_Usuario2_idx` ON `gameUpDB`.`Suporte` (`usu_idMod` ASC);

CREATE INDEX `fk_Usuario_has_Usuario_Usuario1_idx` ON `gameUpDB`.`Suporte` (`usu_id` ASC);


-- -----------------------------------------------------
-- Table `gameUpDB`.`CodigoSeguranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameUpDB`.`CodigoSeguranca` (
  `cse_id` INT NOT NULL AUTO_INCREMENT,
  `cse_codigo` VARCHAR(30) NOT NULL,
  `cse_dtCriacao` DATETIME NOT NULL,
  `cse_dtValidade` DATETIME NOT NULL,
  `cse_status` INT NOT NULL,
  `usu_id` INT NOT NULL,
  PRIMARY KEY (`cse_id`, `usu_id`),
  CONSTRAINT `fk_CodigoSeguranca_Usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `gameUpDB`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CodigoSeguranca_Usuario1_idx` ON `gameUpDB`.`CodigoSeguranca` (`usu_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into tipousuario(tus_descricao) values("Colaborador");
insert into tipousuario(tus_descricao) values("Gerente");
insert into tipousuario(tus_descricao) values("Representante");
insert into tipousuario(tus_descricao) values("Administrador");
insert into tipousuario(tus_descricao) values("Moderador");

insert into nivel(niv_xp) values(0);
insert into nivel(niv_xp) values(150);
insert into nivel(niv_xp) values(300);
insert into nivel(niv_xp) values(450);
insert into nivel(niv_xp) values(600);
insert into nivel(niv_xp) values(750);
insert into nivel(niv_xp) values(900);
insert into nivel(niv_xp) values(1050);
insert into nivel(niv_xp) values(1200);
insert into nivel(niv_xp) values(1350);
insert into nivel(niv_xp) values(1500);

insert into tipoitem(tip_descricao) values("Vale-Presente");
insert into tipoitem(tip_descricao) values("Beneficio");

insert into empresa(emp_nome, emp_cnpj) values("Financeira ME","91732336000102"); 
insert into empresa(emp_nome, emp_cnpj) values("GameUp Enterprise","10876397000133"); 
insert into empresa(emp_nome, emp_cnpj) values("Padaria ME","67415115000118"); 

insert into setor(set_nome, emp_id) values("Almoxarifado", 1);
insert into setor(set_nome, emp_id) values("Vendas", 1);
insert into setor(set_nome, emp_id) values("TI", 1);
insert into setor(set_nome, emp_id) values("RH", 1);
insert into setor(set_nome, emp_id) values("Almoxarifado", 2);
insert into setor(set_nome, emp_id) values("Vendas", 2);
insert into setor(set_nome, emp_id) values("TI", 2);
insert into setor(set_nome, emp_id) values("RH", 2);
insert into setor(set_nome, emp_id) values("Almoxarifado", 3);
insert into setor(set_nome, emp_id) values("Vendas", 3);
insert into setor(set_nome, emp_id) values("TI", 3);
insert into setor(set_nome, emp_id) values("RH", 3);

insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Lucas Pedroso","lucas.pedroso@gmail.com", '1999-02-15', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 1, 3, 1, 3); -- empresa 1 '-'
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Marcos Vinicius","marcos.vinicius@gmail.com", '1998-06-05', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 6, 1, 1, 1); -- empresa 2 '-'
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Yago Chedid","yago.chedid@gmail.com", '2000-03-02', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 9, 1, 1, 3); -- empresa 3 '-'

-- Empresa 1:
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Aline Allana Melo", "alinemelo@gmail.com", '1980-11-14', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 1, 2, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Vicente Oliver da Mota", "vicenteoliver@gmail.com", '2000-05-21', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 2, 2, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Gustavo Nicolas Brito", "gustavobrito@gmail.com", '1991-08-09', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 2, 1, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Andreia Aparecida da Cruz", "andreiacruz@gmail.com", '1980-11-16', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 2, 1, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Bruna Francisca Ana da Costa", "brunacosta_@gmail.com", '1980-09-10', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 3, 2, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Nathan José Joaquim Corte Real", "nathanjose@gmail.com", '1997-03-14', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 3, 1, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Camila Gabrielly Bernardes", "camilabernardes@gmail.com", '1982-09-26', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 3, 1, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Ruan Eduardo Porto", "ruanporto@gmail.com", '1981-01-10', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 4, 2, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Daniel Noah Pires", "danielpires@gmail.comr", '1989-12-02', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 4, 1, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Severino Thiago Ramos", "severinoramos@gmail.com", '1985-01-07', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 4, 1, 1, 3);

-- Empresa 2:
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Luciana Alícia dos Santos", "luciana.santos-77@gmail.com", '1992-12-16', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 5, 2, 1, 1);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Larissa Raquel das Neves", "larissa.neves@gmail.com", '1988-08-02', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 6, 2, 1, 1);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Osvaldo Anthony das Neves", "osvaldo.neves@gmail.com", '1984-02-16', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 6, 1, 1, 1);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Caleb Cauã Lima", "caleb.lima@gmail.com", '1989-10-04', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 6, 1, 1, 1);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Thales Antonio Yago Nunes", "thales.nunes@gmail.com", '1982-07-16', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 7, 2, 1, 1);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Bruno Erick Antonio da Silva", "bruno.silva@gmail.com", '1982-07-14', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 7, 1, 1, 1);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Camila Aurora Ferreira", "camila.ferreira-80@gmail.com", '1989-07-18', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 7, 1, 1, 1);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Calebe Thiago Murilo Drumond", "calebe.drumond@gmail.com", '1984-11-13', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 8, 2, 1, 1);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Giovanni Luís Monteiro", "giovanni.monteiro@gmail.com", '1981-02-14', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 8, 1, 1, 1);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Hugo Thales Oliver Almeida", "hugo.almeida@gmail.com", '1986-07-03', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 8, 1, 1, 1);

-- Empresa 3:
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Eduardo Henry das Neves", "eduardoneves@gmail.com", '1995-12-06', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 9, 2, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Rafael Cauê Leonardo Fogaça", "rafaelfogaca@gmail.com", '1984-10-17', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 10, 2, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Bernardo Nathan Gael Silveira", "bernardosilveira@gmail.com", '1984-01-09', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 10, 1, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Joe Renato Miguel da Mota", "jorgermota@gmail.com", '1986-07-19', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 10, 1, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Luís Daniel Arthur Nascimento", "luisnascimento@gmail.com", '1986-02-04', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 11, 2, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Fernanda Luciana Emanuelly Costa", "fernandacosta@gmail.com", '1988-11-25', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 11, 1, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Severino Fábio Araújo", "severinoaraujo@gmail.com", '1990-09-19', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 11, 1, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Eduarda Isadora Sophie Vieira", "eduardavieira@gmail.com", '1988-12-13', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 12, 2, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Emanuel Séio Carlos Sales", "emanuelsales@gmail.com", '1987-09-12', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 12, 1, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Marcela Simone Jesus", "marcelajesus@gmail.com", '1983-06-10', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 12, 1, 1, 3);

insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Kaique Fábio Ferreira", "kaique.fabio@gmail.com", '2002-11-09', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 1, 1, 3, 1, 3);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Juliana Rayssa Lívia Aparício", "juliana.rayssa@gmail.com", '1942-05-24', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 2, 5, 3, 1, 1);
insert into usuario(usu_nome, usu_email, usu_dataNascimento, usu_senha, emp_id, set_id, tus_id, niv_id, usu_statusUsuario) values("Valentina Bruna Sueli Santos", "valentina.bruna@gmail.com", '1986-03-25', '079f90f9cbe6abd008f03060b2112d50827e48a4fa01851546923de3f45bfea7156c6b9798e2f460a711d4ddfc90bc632ef1b9a59fb0cb045637a7bfe1e5ea44', 3, 9, 3, 1, 3);

insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("Bon appétit!", "Uma reserva de jantar para um ótimo fim de semana.", "Uma reserva no restaurante Madero, as 20h00, com tudo incluso", 500, "../../Assets/Imagens/jantar.jpg", 1, 1, 1, 2);
insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("O tempo voa!", "Acrescente +30 minutos na sua pausa de almoço.", "Acrescente +30 minutos na sua pausa de almoço.", 250, "../../Assets/Imagens/tempo.jpg", 1, 1, 1, 2);
insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("Descanso merecido!", "Consiga uma folga em um dia de sua escolha.", "Consiga uma folga em um dia de sua escolha.", 400, "../../Assets/Imagens/piscina.jpg", 1, 1, 1, 2);
insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("Viagem de Final de Semana", "Uma reserva em um hotel para o fim de semana.", "Uma reserva no hotel Ibis para 5 pessoas.", 1000, "../../Assets/Imagens/piscina.jpg", 1, 1, 1, 2);

insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("Bon appétit!", "Uma reserva de jantar para um ótimo fim de semana.", "Uma reserva no restaurante Madero, as 20h00, com tudo incluso", 500, "../../Assets/Imagens/jantar.jpg", 1, 2, 2, 2);
insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("O tempo voa!", "Acrescente +30 minutos na sua pausa de almoço.", "Acrescente +30 minutos na sua pausa de almoço.", 250, "../../Assets/Imagens/tempo.jpg", 1, 2, 2, 2);
insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("Descanso merecido!", "Consiga uma folga em um dia de sua escolha.", "Consiga uma folga em um dia de sua escolha.", 400, "../../Assets/Imagens/piscina.jpg", 1, 2, 2, 2);
insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("Viagem de Final de Semana", "Uma reserva em um hotel para o fim de semana.", "Uma reserva no hotel Ibis para 5 pessoas.", 1000, "../../Assets/Imagens/piscina.jpg", 1, 2, 2, 2);

insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("Bon appétit!", "Uma reserva de jantar para um ótimo fim de semana.", "Uma reserva no restaurante Madero, as 20h00, com tudo incluso", 500, "../../Assets/Imagens/jantar.jpg", 1, 3, 3, 2);
insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("O tempo voa!", "Acrescente +30 minutos na sua pausa de almoço.", "Acrescente +30 minutos na sua pausa de almoço.", 250, "../../Assets/Imagens/tempo.jpg", 1, 3, 3, 2);
insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("Descanso merecido!", "Consiga uma folga em um dia de sua escolha.", "Consiga uma folga em um dia de sua escolha.", 400, "../../Assets/Imagens/piscina.jpg", 1, 3, 3, 2);
insert into produtos(pro_nome, pro_subTitulo,pro_descricao,pro_valorMoeda,pro_logo,pro_status,emp_id,usu_id,tip_id) 
values("Viagem de Final de Semana", "Uma reserva em um hotel para o fim de semana.", "Uma reserva no hotel Ibis para 5 pessoas.", 1000, "../../Assets/Imagens/piscina.jpg", 1, 3, 3, 2);

insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 15, "Criação do Produto", 1, 1);
insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 7, "Criação do Produto", 2, 1);
insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 9, "Criação do Produto", 3, 1);
insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 10, "Criação do Produto", 4, 1);

insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 15, "Criação do Produto", 5, 2);
insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 7, "Criação do Produto", 6, 2);
insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 9, "Criação do Produto", 7, 2);
insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 10, "Criação do Produto", 8, 2);

insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 15, "Criação do Produto", 9, 3);
insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 7, "Criação do Produto", 10, 3);
insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 9, "Criação do Produto", 11, 3);
insert into movestoque(mes_dHCriacao, mes_qtdEntrada, mes_descricao, pro_id, emp_id) values (curdate(), 10, "Criação do Produto", 12, 3);

update usuario set usu_qtdMoeda = 1302, usu_qtdXp = 1002, usu_qtdPontos = 1192 where usu_id = 14;
update usuario set usu_qtdMoeda = 1483, usu_qtdXp = 1481, usu_qtdPontos = 1424 where usu_id = 15;
update usuario set usu_qtdMoeda = 1011, usu_qtdXp = 1251, usu_qtdPontos = 1082 where usu_id = 16;
update usuario set usu_qtdMoeda =  738, usu_qtdXp =  667, usu_qtdPontos =  692 where usu_id = 17;
update usuario set usu_qtdMoeda =  738, usu_qtdXp =  695, usu_qtdPontos =  781 where usu_id = 18;
update usuario set usu_qtdMoeda =  981, usu_qtdXp =  902, usu_qtdPontos = 1271 where usu_id = 19;
update usuario set usu_qtdMoeda = 1334, usu_qtdXp = 1308, usu_qtdPontos = 1323 where usu_id = 20;
update usuario set usu_qtdMoeda =  938, usu_qtdXp =  967, usu_qtdPontos = 1114 where usu_id = 21;
update usuario set usu_qtdMoeda = 1121, usu_qtdXp = 1344, usu_qtdPontos = 1367 where usu_id = 22;
update usuario set usu_qtdMoeda =  892, usu_qtdXp = 1029, usu_qtdPontos = 1133 where usu_id = 23;

INSERT INTO missao (`mis_id`,`mis_nome`,`mis_descricao`,`mis_dt_Criacao`,`mis_dt_Inicio`,`mis_dt_Final`,`mis_qtd_Pontos`,`mis_qtd_Exp`,`mis_qtd_moedas`,`mis_tipo`,`mis_status`,`emp_id`,`usu_criador_id`) VALUES (1,'MISSAO 1','A missao deve ser resolvida de maneira especifica','2020-02-01 22:46:51','2020-02-01 22:46:51','2020-02-01 00:00:00',300,200,100,'INDIVIDUAL','COMPLETA',2,15);
INSERT INTO missao (`mis_id`,`mis_nome`,`mis_descricao`,`mis_dt_Criacao`,`mis_dt_Inicio`,`mis_dt_Final`,`mis_qtd_Pontos`,`mis_qtd_Exp`,`mis_qtd_moedas`,`mis_tipo`,`mis_status`,`emp_id`,`usu_criador_id`) VALUES (2,'MISSAO 2','A missao deve ser resolvida de maneira especifica','2020-03-01 22:47:19','2020-03-01 22:47:19','2020-03-01 00:00:00',400,300,200,'INDIVIDUAL','COMPLETA',2,15);
INSERT INTO missao (`mis_id`,`mis_nome`,`mis_descricao`,`mis_dt_Criacao`,`mis_dt_Inicio`,`mis_dt_Final`,`mis_qtd_Pontos`,`mis_qtd_Exp`,`mis_qtd_moedas`,`mis_tipo`,`mis_status`,`emp_id`,`usu_criador_id`) VALUES (3,'MISSAO 3','A missao deve ser resolvida de maneira especifica','2020-04-01 22:47:49','2020-04-01 22:47:49','2020-04-01 00:00:00',400,300,200,'INDIVIDUAL','COMPLETA',2,15);
INSERT INTO missao (`mis_id`,`mis_nome`,`mis_descricao`,`mis_dt_Criacao`,`mis_dt_Inicio`,`mis_dt_Final`,`mis_qtd_Pontos`,`mis_qtd_Exp`,`mis_qtd_moedas`,`mis_tipo`,`mis_status`,`emp_id`,`usu_criador_id`) VALUES (4,'MISSAO 4','A missao deve ser resolvida de maneira especifica','2020-05-01 22:48:29','2020-05-01 22:48:29','2020-05-01 00:00:00',600,500,300,'INDIVIDUAL','COMPLETA',2,15);
INSERT INTO missao (`mis_id`,`mis_nome`,`mis_descricao`,`mis_dt_Criacao`,`mis_dt_Inicio`,`mis_dt_Final`,`mis_qtd_Pontos`,`mis_qtd_Exp`,`mis_qtd_moedas`,`mis_tipo`,`mis_status`,`emp_id`,`usu_criador_id`) VALUES (5,'MISSAO 5','A missao deve ser resolvida de maneira especifica','2020-06-01 22:49:09','2020-06-01 22:49:09','2020-06-01 00:00:00',100,400,500,'INDIVIDUAL','COMPLETA',2,15);

INSERT INTO missao_usuario (`mus_id`,`mus_dt_Atribuicao`,`mus_dt_Conclusao`,`mus_dt_Validacao`,`mus_status`,`mis_id`,`usu_id`) VALUES (1,'2020-02-01 22:46:51','2020-02-01 22:56:21','2020-02-01 23:00:44','VALIDADA',1,2);
INSERT INTO missao_usuario (`mus_id`,`mus_dt_Atribuicao`,`mus_dt_Conclusao`,`mus_dt_Validacao`,`mus_status`,`mis_id`,`usu_id`) VALUES (2,'2020-03-01 22:47:19','2020-03-01 22:56:33','2020-03-01 23:00:56','VALIDADA',2,2);
INSERT INTO missao_usuario (`mus_id`,`mus_dt_Atribuicao`,`mus_dt_Conclusao`,`mus_dt_Validacao`,`mus_status`,`mis_id`,`usu_id`) VALUES (3,'2020-04-01 22:47:49','2020-04-01 22:56:49','2020-04-01 23:01:08','VALIDADA',3,2);
INSERT INTO missao_usuario (`mus_id`,`mus_dt_Atribuicao`,`mus_dt_Conclusao`,`mus_dt_Validacao`,`mus_status`,`mis_id`,`usu_id`) VALUES (4,'2020-05-01 22:48:29','2020-05-01 22:57:06','2020-05-01 23:01:34','VALIDADA',4,2);
INSERT INTO missao_usuario (`mus_id`,`mus_dt_Atribuicao`,`mus_dt_Conclusao`,`mus_dt_Validacao`,`mus_status`,`mis_id`,`usu_id`) VALUES (5,'2020-06-01 22:49:09','2020-06-01 22:57:21','2020-06-01 23:02:00','VALIDADA',5,2);

UPDATE usuario set usu_qtdPontos = '300', usu_qtdXp = '200', usu_qtdMoeda = '100' WHERE usu_id = '2';
UPDATE usuario set usu_qtdPontos = '400', usu_qtdXp = '300', usu_qtdMoeda = '200' WHERE usu_id = '2';
UPDATE usuario set usu_qtdPontos = '400', usu_qtdXp = '300', usu_qtdMoeda = '200' WHERE usu_id = '2';
UPDATE usuario set usu_qtdPontos = '600', usu_qtdXp = '500', usu_qtdMoeda = '300' WHERE usu_id = '2';
UPDATE usuario set usu_qtdPontos = '100', usu_qtdXp = '400', usu_qtdMoeda = '500' WHERE usu_id = '2';
